# Generated by Django 2.1 on 2022-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dname', models.TextField(primary_key=True, serialize=False)),
                ('dplace', models.TextField()),
                ('specialisation', models.TextField()),
                ('degrees', models.TextField()),
                ('place', models.TextField()),
                ('hospital', models.TextField()),
                ('hospcity', models.TextField()),
                ('phno', models.TextField()),
                ('email', models.TextField()),
                ('ambulance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('pswd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('phno', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('vid', models.TextField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('date_time', models.TextField()),
                ('Temprature', models.TextField()),
                ('BloodPressure', models.TextField()),
                ('Heartrate', models.TextField()),
            ],
        ),
    ]
