# Generated by Django 2.1 on 2022-11-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='doc',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
